# Generated by Django 6.0.1 on 2026-02-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlinemain', '0002_alter_deadlinetask_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinfo',
            name='course',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='deadlinemain.courseinfo', to_field='course_code'),
        ),
    ]
