# Generated by Django 6.0.1 on 2026-02-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlinemain', '0004_alter_groupinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='deadlinemain.student', to_field='student_id'),
        ),
    ]
