# Generated by Django 6.0.1 on 2026-02-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlinemain', '0005_alter_groupinfo_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='deadlinemain.student', to_field='student_id'),
        ),
    ]
