# Generated by Django 6.0.1 on 2026-02-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlinemain', '0006_courseinfo_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='deadlinemain.courseinfo'),
        ),
    ]
