# Generated by Django 6.0.1 on 2026-02-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlinemain', '0007_alter_courseinfo_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlinetask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='deadlinemain.student', to_field='student_id'),
        ),
    ]
